### ISSUE TITLE
 Vertex buffer is not big enough for the draw call

### ISSUE THREAD

**Issue by 542154968** [agargaro/instanced-mesh#77]
<img width="826" alt="image" src="https://github.com/user-attachments/assets/72179254-4dca-4e16-bd87-8759491fcca5" />

"three": "^0.170.0"

```js
  import { InstancedMesh2 } from '@three.ez/instanced-mesh';

 const renderer = new THREE.WebGLRenderer({
    antialias: true,
    powerPreference: 'high-performance',
    logarithmicDepthBuffer: true,
    stencil: true,
  });
  // window.devicePixelRatio
  renderer.setPixelRatio(2);
  renderer.setSize(window.innerWidth, window.innerHeight);

  const geometry = new THREE.BoxGeometry(0.5, 0.5, 0.5);
  const material = new THREE.MeshBasicMaterial({ color: 'green' });
  const count = 10;
  const myInstancedMesh = new InstancedMesh2(geometry, material, { capacity: count, renderer });
  myInstancedMesh.addInstances(count, (obj, index) => {
    obj.position.x = index;
  }); // add instances and expand buffer if necessary
  myInstancedMesh.computeBVH();

  scene.add(myInstancedMesh);
```

**Comment by agargaro** [comment]
Hi! 😄 

I can't reproduce the bug. 
Can you please reproduce it using this example?

https://stackblitz.com/edit/stackblitz-starters-eramw9rd?file=script.js

**Comment by 542154968** [comment]
It might be due to the version of dependencies installed via pnpm. Using this approach indeed allows it to run

<img width="903" alt="image" src="https://github.com/user-attachments/assets/0b7dcdbe-736a-4576-8c39-f396f6f510ca" />

**Comment by 542154968** [comment]
I found the issue. When using ssaoPass, this error occurs.
<img width="1751" alt="image" src="https://github.com/user-attachments/assets/d415bd04-e60a-4c72-900c-1d0b81f3d481" />


```js
import * as THREE from 'three';
import { InstancedMesh2 } from '@three.ez/instanced-mesh';
import { EffectComposer } from 'three/addons/postprocessing/EffectComposer.js';
import { RenderPass } from 'three/addons/postprocessing/RenderPass.js';
import { SSAOPass } from 'three/addons/postprocessing/SSAOPass.js';

const scene = new THREE.Scene();
const camera = new THREE.PerspectiveCamera(
  75,
  window.innerWidth / window.innerHeight,
  0.1,
  1000
);
camera.translateZ(10);

const renderer = new THREE.WebGLRenderer({
  antialias: true,
  powerPreference: 'high-performance',
  logarithmicDepthBuffer: true,
  stencil: true,
});
renderer.setPixelRatio(2);
renderer.setSize(window.innerWidth, window.innerHeight);
renderer.setAnimationLoop(animate);
document.body.appendChild(renderer.domElement);

const composer = new EffectComposer(renderer);
const ssaoPass = new SSAOPass(
  scene,
  camera,
  window.innerWidth,
  window.innerHeight
);
// 数值越大效果越好 性能消耗越高 4-8低端设备  12-16中端 20-32高端
ssaoPass.kernelRadius = 16;
/**
 * 场景渲染
 */
const renderScene = new RenderPass(scene, camera);
composer.setSize(window.innerWidth, window.innerHeight);
composer.addPass(renderScene);
composer.addPass(ssaoPass);

const geometry = new THREE.BoxGeometry(0.5, 0.5, 0.5);
const material = new THREE.MeshBasicMaterial({ color: 'green' });
const count = 10;
const myInstancedMesh = new InstancedMesh2(geometry, material, {
  capacity: count,
  renderer,
});

myInstancedMesh.addInstances(count, (obj, index) => {
  obj.position.x = index;
}); // add instances and expand buffer if necessary

scene.add(myInstancedMesh);

function animate() {
  // renderer.render(scene, camera);
  composer.render();
}

```

**Comment by 542154968** [comment]
<img width="1779" alt="image" src="https://github.com/user-attachments/assets/20c36a2d-a6a9-49cb-b012-036a2d0cd9fb" />
The issue still persists on my computer.
<img width="291" alt="image" src="https://github.com/user-attachments/assets/9acef766-3053-4f1d-9aa5-91bba73c1d81" />

**Comment by agargaro** [comment]
It could be a webkit bug. Do the official three.js examples work without any problems instead? 

Could you try the example I linked, using the official instancedMesh and see if there is the error?

**Comment by 542154968** [comment]
> It could be a webkit bug? Do the official three.js examples work without any problems instead?
> 
> Could you try the example I linked, using the official instancedMesh and see if there is the error?

<img width="1773" alt="image" src="https://github.com/user-attachments/assets/8cdc9c91-48b2-4dc3-bc13-842714df7e1b" />
Using THREE.InstancedMesh works without any issues.

**Comment by agargaro** [comment]
Thank you for the tests!
These days I am working on other features, I will investigate in the next few days :)

**Comment by agargaro** [comment]
@542154968 
Hi! I fixed the problem with `scene.overrideMaterial`. 
I will publish the new package tomorrow, after that can you help me test it?

**Comment by 542154968** [comment]
> @542154968 Hi! I fixed the problem with `scene.overrideMaterial`. I will publish the new package tomorrow, after that can you help me test it?

Of course! Looking forward to it.

**Comment by agargaro** [comment]
@542154968 New package released :)

I updated the previous example: https://stackblitz.com/edit/stackblitz-starters-4ppmrgms?file=script.js

**Comment by 542154968** [comment]
> @542154968 New package released :)
> 
> I updated the previous example: https://stackblitz.com/edit/stackblitz-starters-4ppmrgms?file=script.js
> 
> Edit: I tested it, and with more than one InstancedMesh2 it doesn't work... I'm working on a fix

Unfortunately, the issue still persists in the demo you provided. Thank you very much, sir.

**Comment by agargaro** [comment]
Okay. I'll investigate with a friend who has the MacBook.

**Comment by agargaro** [comment]
@542154968 new version released (0.3.0-alpha.8), and tested it on @luigidenora mac.

Let me know if now it works.

**Comment by 542154968** [comment]
> @542154968 new version released (0.3.0-alpha.8), and tested it on @luigidenora mac.
> 
> Let me know if now it works.

Thank you very much！
